package services.responses;

public enum ErrorType {
    CAPACITY_FULL,
    DUPLICATE_SECTIONS,
    DUPLICATE_SUBJECTS,
    SCHEDULE_CONFLICT,
    UNAVAILABLE_SECTION,

    ID_NOT_FOUND,
    FILE_NOT_FOUND,

    CANNOT_READ,
    CANNOT_WRITE,
    SYSTEM_ERROR
}
